title: Arti Karahoda
description: Cyber Security & Data Protection
show_downloads: false
show_repo: false
theme: jekyll-theme-midnight
highlighter: rouge
url: https://artikrh.github.io
google_analytics: UA-151966598-1
github:
  is_project_page: false
github_username: artikrh
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
webrick:
  headers:
    Content-Security-Policy: default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';